FROM node:22-alpine AS frontend-build
WORKDIR /app
ARG VITE_MIN_VIEWPORT_WIDTH=1100
ARG VITE_MIN_PARTICIPANT_AGE=18
ARG VITE_CONSENT_TEXT_VERSION=1.0
ARG VITE_RESEARCH_INSTITUTION="[Research institution]"
ARG VITE_INVESTIGATOR="[Investigator]"
ARG VITE_EXPECTED_DURATION="[Expected duration]"
ARG VITE_DATA_HANDLING="[Anonymity and data handling information]"
ARG VITE_WITHDRAWAL_INFO="[Withdrawal information]"
ARG VITE_ETHICS_CONTACT="[Ethics and contact information]"
ARG VITE_FINAL_TEXT="Your responses have been recorded."
ARG VITE_TRAINING_JOY_ASSET=""
ARG VITE_TRAINING_CH_ASSET=""
ENV VITE_MIN_VIEWPORT_WIDTH=$VITE_MIN_VIEWPORT_WIDTH \
    VITE_MIN_PARTICIPANT_AGE=$VITE_MIN_PARTICIPANT_AGE \
    VITE_CONSENT_TEXT_VERSION=$VITE_CONSENT_TEXT_VERSION \
    VITE_RESEARCH_INSTITUTION=$VITE_RESEARCH_INSTITUTION \
    VITE_INVESTIGATOR=$VITE_INVESTIGATOR \
    VITE_EXPECTED_DURATION=$VITE_EXPECTED_DURATION \
    VITE_DATA_HANDLING=$VITE_DATA_HANDLING \
    VITE_WITHDRAWAL_INFO=$VITE_WITHDRAWAL_INFO \
    VITE_ETHICS_CONTACT=$VITE_ETHICS_CONTACT \
    VITE_FINAL_TEXT=$VITE_FINAL_TEXT \
    VITE_TRAINING_JOY_ASSET=$VITE_TRAINING_JOY_ASSET \
    VITE_TRAINING_CH_ASSET=$VITE_TRAINING_CH_ASSET
COPY frontend/package*.json ./
RUN npm ci
COPY frontend/ ./
RUN npm run build

FROM caddy:2.10-alpine
COPY deploy/Caddyfile /etc/caddy/Caddyfile
COPY --from=frontend-build /app/dist /srv
COPY stimuli/ /srv/stimuli/
COPY training/ /srv/training/
